In [197]:
%pip install numpy 
%pip install pandas

Requirement already satisfied: numpy in d:\github desk\movie_recommendation_system\movie\lib\site-packages (2.0.1)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in d:\github desk\movie_recommendation_system\movie\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [198]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\github desk\movie_recommendation_system\movie\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from scikit-learn) (2.0.1)
Requirement already satisfied: scipy>=1.6.0 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\github desk\movie_recommendation_system\movie\lib\site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [199]:
import numpy as np 
import pandas as pd

In [200]:
df_standard1=pd.read_csv('TMDB_movies_Hindi.csv')
df_standard2=pd.read_csv('TMDB.csv')

In [201]:
df_standard=pd.concat([df_standard1,df_standard2],axis=0)

In [202]:
df_standard.columns

Index(['movie_id', 'title', 'overview', 'keywords', 'genres', 'release_date',
       'original_language', 'original_title', 'production_companies',
       'revenue', 'status', 'tagline', 'spoken_languages', 'runtime', 'budget',
       'vote_count', 'vote_average', 'popularity', 'adult_tf', 'poster_path',
       'cast', 'crew', 'Unnamed: 0'],
      dtype='object')

In [203]:
df_standard.sample(10)

,movie_id,title,overview,keywords,genres,release_date,original_language,original_title,production_companies,revenue,...,runtime,budget,vote_count,vote_average,popularity,adult_tf,poster_path,cast,crew,Unnamed: 0
8457,342521,Keanu,Friends hatch a plot to retrieve a stolen cat ...,"[{'id': 2708, 'name': 'hitman'}, {'id': 3149, ...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",2016-04-21,en,Keanu,"[{'id': 12, 'logo_path': '/iaYpEp3LQmb8AfAtmTv...",20609977,...,100,15000000,917,6.100,14.304,False,/dPWlBmCixh9k3Jjb7c7jkIaxBbL.jpg,"[{'adult': False, 'gender': 2, 'id': 291263, '...","[{'adult': False, 'gender': 2, 'id': 18264, 'k...",8458.0
8419,81218,Devilish Education,Gosia is a beautiful and innocent young maid o...,[],"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",1995-01-11,pl,Diabelska edukacja,"[{'id': 58245, 'logo_path': None, 'name': 'Her...",0,...,29,0,10,6.300,14.352,False,/bzfxkARdavCD4wnoMTgublrlvtW.jpg,"[{'adult': False, 'gender': 1, 'id': 591270, '...","[{'adult': False, 'gender': 2, 'id': 591269, '...",8420.0
2698,48340,Sanctum,Master diver Frank McGuire (Richard Roxburgh) ...,"[{'id': 1963, 'name': 'expedition'}, {'id': 19...","[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",2011-02-03,en,Sanctum,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...",108609310,...,108,30000000,888,5.973,29.311,False,/zRUNv1CbeVtmTCNr6RLHnxV2QYm.jpg,"[{'adult': False, 'gender': 2, 'id': 12206, 'k...","[{'adult': False, 'gender': 2, 'id': 2710, 'kn...",2699.0
8225,401898,Thelma,A college student starts to experience extreme...,"[{'id': 186, 'name': 'christianity'}, {'id': 4...","[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",2017-09-15,no,Thelma,"[{'id': 228, 'logo_path': '/zT2bcTDEbBkfZi2APB...",1471656,...,116,5741614,839,6.844,14.581,False,/yzSfG8TLAqw7nMQh2lxirQkQpgs.jpg,"[{'adult': False, 'gender': 1, 'id': 1198672, ...","[{'adult': False, 'gender': 0, 'id': 5985, 'kn...",8226.0
5495,290729,Sniper: Legacy,After several military leaders are assassinate...,"[{'id': 1589, 'name': 'sniper'}, {'id': 157218...","[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",2014-09-29,en,Sniper: Legacy,"[{'id': 769, 'logo_path': '/j8zjbr6CzgiOj4kdtk...",0,...,94,0,175,5.937,18.413,False,/a9L1t3vRaZRU1Fa0kolfQGiTCnQ.jpg,"[{'adult': False, 'gender': 2, 'id': 13022, 'k...","[{'adult': False, 'gender': 2, 'id': 21203, 'k...",5496.0
2480,440471,Escape Plan 2: Hades,Ray Breslin manages an elite team of security ...,"[{'id': 310, 'name': 'artificial intelligence'...","[{'id': 28, 'name': 'Action'}]",2018-06-05,en,Escape Plan 2: Hades,"[{'id': 491, 'logo_path': '/rUp0lLKa1pr4UsPm8f...",17500000,...,96,20000000,1200,5.108,33.397,False,/A6tb8JNrie2qT8JC2tGqshayuck.jpg,"[{'adult': False, 'gender': 2, 'id': 16483, 'k...","[{'adult': False, 'gender': 2, 'id': 3956, 'kn...",2481.0
845,96162,Chitchor,Geeta ends up with two suitors after her fathe...,"[{'id': 4344, 'name': 'musical'}]","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",1/1/1976,hi,Chitchor,"[{'id': 66728, 'logo_path': None, 'name': 'Raj...",0,...,105,0,1,5.000,0.840,False,/knjv0IUp6x2zAY66ZrgYoDJyZjP.jpg,"[{'adult': False, 'gender': 2, 'id': 105650, '...","[{'adult': False, 'gender': 2, 'id': 110229, '...",NaN
1308,157350,Divergent,In a world divided into factions based on pers...,"[{'id': 818, 'name': 'based on novel or book'}...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2014-03-14,en,Divergent,"[{'id': 491, 'logo_path': '/rUp0lLKa1pr4UsPm8f...",288747895,...,139,85000000,11654,6.921,39.173,False,/aNh4Q3iuPKDMPi2SL7GgOpiLukX.jpg,"[{'adult': False, 'gender': 1, 'id': 94185, 'k...","[{'adult': False, 'gender': 2, 'id': 36, 'know...",1309.0
366,24603,All the Best: Fun Begins,All The Best is a rib-tickling comedy based on...,"[{'id': 10325, 'name': 'mistaken identity'}, {...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",10/16/2009,hi,आल थे बेस्ट: फन बेगिंस,"[{'id': 128365, 'logo_path': '/9UnLNX7mfB1Fzie...",0,...,144,7500000,37,6.230,4.259,False,/wS4HXoaijxIbI8lv6H9MFNKAcQa.jpg,"[{'adult': False, 'gender': 2, 'id': 42803, 'k...","[{'adult': False, 'gender': 2, 'id': 42803, 'k...",NaN
2637,11253,Hellboy II: The Golden Army,Hellboy must stop an elven prince from locatin...,"[{'id': 2096, 'name': 'auction'}, {'id': 7005,...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2008-07-11,en,Hellboy II: The Golden Army,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...",160388063,...,120,85000000,4528,6.749,28.227,False,/fGQAO4RgUzspO7L4u5KXirIn34s.jpg,"[{'adult': False, 'gender': 2, 'id': 2372, 'kn...","[{'adult': False, 'gender': 2, 'id': 531, 'kno...",2638.0

In [204]:
# column that going to use

df=df_standard[['movie_id','title','overview','genres','production_companies','cast', 'crew','original_language']]

In [205]:
df

,movie_id,title,overview,genres,production_companies,cast,crew,original_language
0,783461,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 113699, 'logo_path': None, 'name': 'El...","[{'adult': False, 'gender': 1, 'id': 550167, '...","[{'adult': False, 'gender': 2, 'id': 1071, 'kn...",hi
1,592508,Sooryavanshi,"A fearless, faithful albeit slightly forgetful...","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 7294, 'logo_path': '/kK4PRgceWp9KNrycD...","[{'adult': False, 'gender': 2, 'id': 35070, 'k...","[{'adult': False, 'gender': 2, 'id': 35070, 'k...",hi
2,20453,3 Idiots,Rascal. Joker. Dreamer. Genius... You've never...,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...","[{'id': 3781, 'logo_path': None, 'name': 'Vidh...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...","[{'adult': False, 'gender': 2, 'id': 35779, 'k...",hi
3,26022,My Name Is Khan,"Rizwan Khan, a Muslim from the Borivali sectio...","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...","[{'id': 43, 'logo_path': '/4RgIPr55kBakgupWkzd...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...",hi
4,767377,Dhamaka,When a cynical ex-TV news anchor gets an alarm...,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...","[{'id': 7819, 'logo_path': '/ghFZAt4edln0M7BzD...","[{'adult': False, 'gender': 2, 'id': 1846859, ...","[{'adult': False, 'gender': 2, 'id': 53677, 'k...",hi
...,...,...,...,...,...,...,...,...
9995,18674,The Bodyguard from Beijing,A corrupt businessman commits a murder and the...,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'id': 2521, 'logo_path': '/e9lXexogBN1nOXA8a...","[{'adult': False, 'gender': 2, 'id': 1336, 'kn...","[{'adult': False, 'gender': 2, 'id': 1336, 'kn...",cn
9996,354861,Father Figures,Upon learning that their mother has been lying...,"[{'id': 35, 'name': 'Comedy'}]","[{'id': 1088, 'logo_path': '/9WOE5AQUXbOtLU6GT...","[{'adult': False, 'gender': 2, 'id': 887, 'kno...","[{'adult': False, 'gender': 2, 'id': 561, 'kno...",en
9997,17687,The Public Enemy,"Two young Chicago hoodlums, Tom Powers and Mat...","[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...","[{'id': 174, 'logo_path': '/IuAlhI9eVC9Z8UQWOI...","[{'adult': False, 'gender': 2, 'id': 5788, 'kn...","[{'adult': False, 'gender': 2, 'id': 7650, 'kn...",en
9998,535437,Swiped,"James, a college freshman and computer genius,...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 106566, 'logo_path': None, 'name': 'Ni...","[{'adult': False, 'gender': 2, 'id': 1253353, ...","[{'adult': False, 'gender': 0, 'id': 1314158, ...",en
9999,24739,Miracle Mile,"After 30 years of searching, Harry has finally...","[{'id': 10749, 'name': 'Romance'}, {'id': 878,...","[{'id': 3952, 'logo_path': None, 'name': 'Hemd...","[{'adult': False, 'gender': 2, 'id': 11085, 'k...","[{'adult': False, 'gender': 2, 'id': 601, 'kno...",en

In [206]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11322 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              11322 non-null  int64
 1   title                 11322 non-null  object
 2   overview              11237 non-null  object
 3   genres                11322 non-null  object
 4   production_companies  11322 non-null  object
 5   cast                  11322 non-null  object
 6   crew                  11322 non-null  object
 7   original_language     11322 non-null  object
dtypes: int64(1), object(7)
memory usage: 796.1+ KB

In [207]:
df.isnull().sum()

movie_id                 0
title                    0
overview                85
genres                   0
production_companies     0
cast                     0
crew                     0
original_language        0
dtype: int64

In [208]:
df.dropna(inplace=True)
df.shape

C:\Users\ASUS\AppData\Local\Temp\ipykernel_31832\2053667463.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

(11237, 8)

In [209]:
df=df.drop_duplicates()
df.shape

(10209, 8)

In [210]:
df[df['movie_id'].duplicated()]

,movie_id,title,overview,genres,production_companies,cast,crew,original_language
1043,783461,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 113699, 'logo_path': None, 'name': 'El...","[{'adult': False, 'gender': 1, 'id': 550167, '...","[{'adult': False, 'gender': 2, 'id': 1071, 'kn...",hi
1518,592508,Sooryavanshi,"A fearless, faithful albeit slightly forgetful...","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 7294, 'logo_path': '/kK4PRgceWp9KNrycD...","[{'adult': False, 'gender': 2, 'id': 35070, 'k...","[{'adult': False, 'gender': 2, 'id': 35070, 'k...",hi
2502,20453,3 Idiots,Rascal. Joker. Dreamer. Genius... You've never...,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...","[{'id': 3781, 'logo_path': None, 'name': 'Vidh...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...","[{'adult': False, 'gender': 2, 'id': 35779, 'k...",hi
3631,767377,Dhamaka,When a cynical ex-TV news anchor gets an alarm...,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...","[{'id': 7819, 'logo_path': '/ghFZAt4edln0M7BzD...","[{'adult': False, 'gender': 2, 'id': 1846859, ...","[{'adult': False, 'gender': 2, 'id': 53677, 'k...",hi
3856,26022,My Name Is Khan,"Rizwan Khan, a Muslim from the Borivali sectio...","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...","[{'id': 43, 'logo_path': '/4RgIPr55kBakgupWkzd...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...",hi
4260,496331,Brahmāstra Part One: Shiva,The story of Shiva – a young man on the brink ...,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 12154, 'logo_path': '/sOHlz02xc4TmVTL4...","[{'adult': False, 'gender': 2, 'id': 85034, 'k...","[{'adult': False, 'gender': 2, 'id': 8684, 'kn...",hi
4420,1029827,Drishyam 2,7 years after the case related to Vijay Salgao...,"[{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...","[{'id': 3522, 'logo_path': '/d3u51JgEP5KwPfxS1...","[{'adult': False, 'gender': 2, 'id': 42803, 'k...","[{'adult': False, 'gender': 2, 'id': 83595, 'k...",hi
6746,10757,Kabhi Khushi Kabhie Gham,Years after his father disowns his adopted bro...,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 19146, 'logo_path': '/5Ff25ornzVNhm5sk...","[{'adult': False, 'gender': 2, 'id': 35780, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...",hi
7204,360814,Dangal,Dangal is an extraordinary true story based on...,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...",hi
7239,560964,Junglee,A vet returns home to his father's elephant re...,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 63187, 'logo_path': '/21kiiZYx0WVFMurY...","[{'adult': False, 'gender': 2, 'id': 1118194, ...","[{'adult': False, 'gender': 2, 'id': 7413, 'kn...",hi
7829,7508,Like Stars on Earth,Ishaan Awasthi is an eight-year-old whose worl...,"[{'id': 18, 'name': 'Drama'}]","[{'id': 2140, 'logo_path': None, 'name': 'Aami...","[{'adult': False, 'gender': 2, 'id': 52764, 'k...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...",hi
7907,44977,Dhoom 3,"To avenge his father's death, a circus enterta...","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 1569, 'logo_path': '/lvzN86o3jrP44DIvn...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...","[{'adult': False, 'gender': 2, 'id': 35771, 'k...",hi
7976,8079,Om Shanti Om,Reincarnated 30 years after being killed in a ...,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...","[{'id': 2343, 'logo_path': '/fkrlAFxgAtIHgYJGI...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...",hi
8558,432527,Padmaavat,"Rajputana, India, 13th century. The tyrannical...","[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...","[{'id': 6808, 'logo_path': '/xa1Yz7B5eRC2F9oHA...","[{'adult': False, 'gender': 2, 'id': 224223, '...","[{'adult': False, 'gender': 2, 'id': 42804, 'k...",hi
8674,714338,Bulbbul,A child bride grows up to be an enigmatic woma...,"[{'id': 27, 'name': 'Horror'}, {'id': 14, 'nam...","[{'id': 80879, 'logo_path': None, 'name': 'Cle...","[{'adult': False, 'gender': 1, 'id': 2100209, ...","[{'adult': False, 'gender': 1, 'id': 81928, 'k...",hi
8847,11854,Kuch Kuch Hota Hai,"Per her mother's last wish, an 8 year old girl...","[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...","[{'id': 19146, 'logo_path': '/5Ff25ornzVNhm5sk...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...",hi
9051,14073,Jodhaa Akbar,A sixteenth century love story about a marriag...,"[{'id': 10749, 'name': 'Romance'}, {'id': 36, ...","[{'id': 2320, 'logo_path': '/nSAXfUCy16cNRiPlB...","[{'adult': False, 'gender': 2, 'id': 78749, 'k...","[{'adult': False, 'gender': 2, 'id': 5288, 'kn...",hi
9055,11518,Mohabbatein,"At a prestigious all-male university, three fr...","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...","[{'id': 1569, 'logo_path': '/lvzN86o3jrP44DIvn...","[{'adult': False, 'gender': 2, 'id': 35780, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...",hi
9197,19666,Lagaan: Once Upon a Time in India,"In 1890s India, an arrogant British commander ...","[{'id': 12, 'name': 'Adventure'}, {'id': 10749...","[{'id': 2140, 'logo_path': None, 'name': 'Aami...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...","[{'adult': False, 'gender': 2, 'id': 5288, 'kn...",hi
9491,363343,Raees,"Set in the early ’80s and ’90s in Gujarat, Ind...","[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...","[{'id': 2343, 'logo_path': '/fkrlAFxgAtIHgYJGI...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 52774, 'k...",hi
9906,12259,Sholay,After his family is murdered by a notorious an...,"[{'id': 28, 'name': 'Action'}]","[{'id': 67524, 'logo_path': None, 'name': 'Sip...","[{'adult': False, 'gender': 2, 'id': 35780, 'k...","[{'adult': False, 'gender': 2, 'id': 85446, 'k...",hi
9979,8453,Fanaa,Zooni Ali Beg is a blind Kashmiri girl who tra...,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","[{'id': 1569, 'logo_path': '/lvzN86o3jrP44DIvn...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...","[{'adult': False, 'gender': 2, 'id': 35771, 'k...",hi

In [211]:
df = df[~df['movie_id'].duplicated(keep='first')]

In [212]:
df[df['movie_id']==783461]

,movie_id,title,overview,genres,production_companies,cast,crew,original_language
0,783461,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 113699, 'logo_path': None, 'name': 'El...","[{'adult': False, 'gender': 1, 'id': 550167, '...","[{'adult': False, 'gender': 2, 'id': 1071, 'kn...",hi

In [213]:
df['movie_id'].drop_duplicates()

0       783461
1       592508
2        20453
3        26022
4       767377
         ...
9990    667969
9994    736820
9996    354861
9997     17687
9999     24739
Name: movie_id, Length: 10187, dtype: int64

In [214]:
df

,movie_id,title,overview,genres,production_companies,cast,crew,original_language
0,783461,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 113699, 'logo_path': None, 'name': 'El...","[{'adult': False, 'gender': 1, 'id': 550167, '...","[{'adult': False, 'gender': 2, 'id': 1071, 'kn...",hi
1,592508,Sooryavanshi,"A fearless, faithful albeit slightly forgetful...","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 7294, 'logo_path': '/kK4PRgceWp9KNrycD...","[{'adult': False, 'gender': 2, 'id': 35070, 'k...","[{'adult': False, 'gender': 2, 'id': 35070, 'k...",hi
2,20453,3 Idiots,Rascal. Joker. Dreamer. Genius... You've never...,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...","[{'id': 3781, 'logo_path': None, 'name': 'Vidh...","[{'adult': False, 'gender': 2, 'id': 52763, 'k...","[{'adult': False, 'gender': 2, 'id': 35779, 'k...",hi
3,26022,My Name Is Khan,"Rizwan Khan, a Muslim from the Borivali sectio...","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...","[{'id': 43, 'logo_path': '/4RgIPr55kBakgupWkzd...","[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn...",hi
4,767377,Dhamaka,When a cynical ex-TV news anchor gets an alarm...,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...","[{'id': 7819, 'logo_path': '/ghFZAt4edln0M7BzD...","[{'adult': False, 'gender': 2, 'id': 1846859, ...","[{'adult': False, 'gender': 2, 'id': 53677, 'k...",hi
...,...,...,...,...,...,...,...,...
9990,667969,Birds of Paradise,Two dancers at an elite ballet academy in Pari...,"[{'id': 18, 'name': 'Drama'}]","[{'id': 6831, 'logo_path': '/fWSI4EjIDEEzCNJC8...","[{'adult': False, 'gender': 1, 'id': 2048372, ...","[{'adult': False, 'gender': 0, 'id': 1113298, ...",en
9994,736820,Confidential Assignment 2: International,Follows Rim Chul Ryung heading back to South K...,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 7036, 'logo_path': '/javbyY0ZCvlFJtly3...","[{'adult': False, 'gender': 2, 'id': 544107, '...","[{'adult': False, 'gender': 1, 'id': 79570, 'k...",ko
9996,354861,Father Figures,Upon learning that their mother has been lying...,"[{'id': 35, 'name': 'Comedy'}]","[{'id': 1088, 'logo_path': '/9WOE5AQUXbOtLU6GT...","[{'adult': False, 'gender': 2, 'id': 887, 'kno...","[{'adult': False, 'gender': 2, 'id': 561, 'kno...",en
9997,17687,The Public Enemy,"Two young Chicago hoodlums, Tom Powers and Mat...","[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...","[{'id': 174, 'logo_path': '/IuAlhI9eVC9Z8UQWOI...","[{'adult': False, 'gender': 2, 'id': 5788, 'kn...","[{'adult': False, 'gender': 2, 'id': 7650, 'kn...",en
9999,24739,Miracle Mile,"After 30 years of searching, Harry has finally...","[{'id': 10749, 'name': 'Romance'}, {'id': 878,...","[{'id': 3952, 'logo_path': None, 'name': 'Hemd...","[{'adult': False, 'gender': 2, 'id': 11085, 'k...","[{'adult': False, 'gender': 2, 'id': 601, 'kno...",en

In [215]:
df.loc[0]

,movie_id,title,overview,genres,production_companies,cast,crew,original_language
0,783461,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 113699, 'logo_path': None, 'name': 'El...","[{'adult': False, 'gender': 1, 'id': 550167, '...","[{'adult': False, 'gender': 2, 'id': 1071, 'kn...",hi
0,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","[{'id': 574, 'logo_path': '/iB6GjNVHs5hOqcEYt2...","[{'adult': False, 'gender': 2, 'id': 65731, 'k...","[{'adult': False, 'gender': 2, 'id': 1721, 'kn...",en

In [216]:
df = df.reset_index()

In [217]:
df=df.drop(columns=['index'])

In [218]:
df.duplicated().sum()

np.int64(0)

In [219]:
df[df['movie_id'].duplicated()]

Empty DataFrame
Columns: [movie_id, title, overview, genres, production_companies, cast, crew, original_language]
Index: []

In [220]:
df[df['movie_id']==783461]

,movie_id,title,overview,genres,production_companies,cast,crew,original_language
0,783461,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 113699, 'logo_path': None, 'name': 'El...","[{'adult': False, 'gender': 1, 'id': 550167, '...","[{'adult': False, 'gender': 2, 'id': 1071, 'kn...",hi

In [221]:
import ast

In [222]:
def fetch_genres(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [223]:
df['genres']=df['genres'].apply(fetch_genres)

In [224]:
def fetch_production_comapanies(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [225]:
df['production_companies']=df['production_companies'].apply(fetch_production_comapanies)

In [226]:
def fetch_cast(text):
    l=[]
    counter=0
    for i in ast.literal_eval(text):
        if counter != 3:
            l.append(i['original_name'])
            counter+=1
        else:
            break
    return l

In [227]:
df['cast']=df['cast'].apply(fetch_cast)

In [228]:
df['crew'][7]

"[{'adult': False, 'gender': 2, 'id': 85446, 'known_for_department': 'Directing', 'name': 'Ramesh Sippy', 'original_name': 'Ramesh Sippy', 'popularity': 2.121, 'profile_path': '/cI0ToZpcju84KjmXSzRuTD8a9V2.jpg', 'credit_id': '52fe44d59251416c7504299d', 'department': 'Directing', 'job': 'Director'}, {'adult': False, 'gender': 2, 'id': 81984, 'known_for_department': 'Writing', 'name': 'Javed Akhtar', 'original_name': 'Javed Akhtar', 'popularity': 1.337, 'profile_path': '/qKnvYtFvox7BhHy2Nx6YbcuSuIB.jpg', 'credit_id': '56128bb1925141478d00bd1b', 'department': 'Writing', 'job': 'Writer'}, {'adult': False, 'gender': 2, 'id': 81986, 'known_for_department': 'Writing', 'name': 'Salim Khan', 'original_name': 'Salim Khan', 'popularity': 1.932, 'profile_path': None, 'credit_id': '56128ba6c3a36868170154eb', 'department': 'Writing', 'job': 'Writer'}, {'adult': False, 'gender': 2, 'id': 86366, 'known_for_department': 'Sound', 'name': 'Kishore Kumar', 'original_name': 'Kishore Kumar', 'popularity': 1.845, 'profile_path': '/ihdicjOHFThEy898RJYmP3rNkv6.jpg', 'credit_id': '591330e8c3a36864fc055d8a', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 2, 'id': 88141, 'known_for_department': 'Sound', 'name': 'Rahul Dev Burman', 'original_name': 'Rahul Dev Burman', 'popularity': 1.96, 'profile_path': '/gR83FY1TkYkcRCsxZVXOXSwTzbV.jpg', 'credit_id': '56418d2292514128a1001cb8', 'department': 'Sound', 'job': 'Music'}, {'adult': False, 'gender': 2, 'id': 88141, 'known_for_department': 'Sound', 'name': 'Rahul Dev Burman', 'original_name': 'Rahul Dev Burman', 'popularity': 1.96, 'profile_path': '/gR83FY1TkYkcRCsxZVXOXSwTzbV.jpg', 'credit_id': '59133149c3a36864a7054e00', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 2, 'id': 131907, 'known_for_department': 'Production', 'name': 'G.P. Sippy', 'original_name': 'G.P. Sippy', 'popularity': 1.166, 'profile_path': None, 'credit_id': '56418cd192514128a1001cac', 'department': 'Production', 'job': 'Producer'}, {'adult': False, 'gender': 0, 'id': 1035289, 'known_for_department': 'Art', 'name': 'Ram Yedekar', 'original_name': 'Ram Yedekar', 'popularity': 1.106, 'profile_path': None, 'credit_id': '56418d5f92514128af001b4e', 'department': 'Art', 'job': 'Production Design'}, {'adult': False, 'gender': 0, 'id': 1035289, 'known_for_department': 'Art', 'name': 'Ram Yedekar', 'original_name': 'Ram Yedekar', 'popularity': 1.106, 'profile_path': None, 'credit_id': '56418d6892514128a4001d4e', 'department': 'Art', 'job': 'Art Direction'}, {'adult': False, 'gender': 0, 'id': 1035292, 'known_for_department': 'Costume & Make-Up', 'name': 'Dinu Indulkar', 'original_name': 'Dinu Indulkar', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418d92c3a3685bd6001e55', 'department': 'Costume & Make-Up', 'job': 'Makeup Artist'}, {'adult': False, 'gender': 0, 'id': 1533853, 'known_for_department': 'Camera', 'name': 'Dwarka Divecha', 'original_name': 'Dwarka Divecha', 'popularity': 0.98, 'profile_path': None, 'credit_id': '56418d35c3a3685bd6001e3e', 'department': 'Camera', 'job': 'Director of Photography'}, {'adult': False, 'gender': 0, 'id': 1533855, 'known_for_department': 'Costume & Make-Up', 'name': 'M.S. Deepak', 'original_name': 'M.S. Deepak', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418d89925141289e001b33', 'department': 'Costume & Make-Up', 'job': 'Makeup Artist'}, {'adult': False, 'gender': 0, 'id': 1533856, 'known_for_department': 'Costume & Make-Up', 'name': 'Lily', 'original_name': 'Lily', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418dbbc3a3685bd9001d93', 'department': 'Costume & Make-Up', 'job': 'Hairstylist'}, {'adult': False, 'gender': 0, 'id': 1533857, 'known_for_department': 'Costume & Make-Up', 'name': 'Sarosh B. Modi', 'original_name': 'Sarosh B. Modi', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418dc5925141289e001b41', 'department': 'Costume & Make-Up', 'job': 'Makeup Artist'}, {'adult': False, 'gender': 0, 'id': 1533858, 'known_for_department': 'Costume & Make-Up', 'name': 'Parvati', 'original_name': 'Parvati', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418deec3a3685bdc001c73', 'department': 'Costume & Make-Up', 'job': 'Hairstylist'}, {'adult': False, 'gender': 0, 'id': 1533859, 'known_for_department': 'Production', 'name': 'Aziz Bhai', 'original_name': 'Aziz Bhai', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418dfac3a3685be2001b67', 'department': 'Production', 'job': 'Production Manager'}, {'adult': False, 'gender': 0, 'id': 1533860, 'known_for_department': 'Production', 'name': 'Suresh Desai', 'original_name': 'Suresh Desai', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418e06c3a3685bd6001e63', 'department': 'Production', 'job': 'Production Manager'}, {'adult': False, 'gender': 0, 'id': 1533861, 'known_for_department': 'Production', 'name': 'Rajan Walia', 'original_name': 'Rajan Walia', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418e19c3a3685be5001b44', 'department': 'Production', 'job': 'Production Manager'}, {'adult': False, 'gender': 0, 'id': 1533862, 'known_for_department': 'Directing', 'name': 'A.R. Balan', 'original_name': 'A.R. Balan', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418e25925141289e001b58', 'department': 'Directing', 'job': 'Assistant Director'}, {'adult': False, 'gender': 0, 'id': 1533863, 'known_for_department': 'Directing', 'name': 'Kishen Bishen', 'original_name': 'Kishen Bishen', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418e2e925141289e001b5d', 'department': 'Directing', 'job': 'Assistant Director'}, {'adult': False, 'gender': 0, 'id': 1533864, 'known_for_department': 'Directing', 'name': 'Khalish Lucknavi', 'original_name': 'Khalish Lucknavi', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418e3692514128af001b77', 'department': 'Directing', 'job': 'Assistant Director'}, {'adult': False, 'gender': 0, 'id': 1533865, 'known_for_department': 'Directing', 'name': 'Sharad Palekar', 'original_name': 'Sharad Palekar', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418e4092514128ad001c4c', 'department': 'Directing', 'job': 'Assistant Director'}, {'adult': False, 'gender': 0, 'id': 1533866, 'known_for_department': 'Directing', 'name': 'D.R. Thakkar', 'original_name': 'D.R. Thakkar', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418e4f92514128a9001be7', 'department': 'Directing', 'job': 'Assistant Director'}, {'adult': False, 'gender': 1, 'id': 1608033, 'known_for_department': 'Sound', 'name': 'Lata Mangeshkar', 'original_name': 'Lata Mangeshkar', 'popularity': 1.4, 'profile_path': '/1JgCDCQpi3KIasQykS3Bd0IHGpp.jpg', 'credit_id': '5913312cc3a36864c6056539', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 2, 'id': 1707463, 'known_for_department': 'Editing', 'name': 'M.S. Shinde', 'original_name': 'M.S. Shinde', 'popularity': 0.6, 'profile_path': None, 'credit_id': '56418d5592514128b2001ccc', 'department': 'Editing', 'job': 'Editor'}, {'adult': False, 'gender': 2, 'id': 1741599, 'known_for_department': 'Sound', 'name': 'Manna Dey', 'original_name': 'Manna Dey', 'popularity': 1.005, 'profile_path': '/dMPt0FzzBEXG7b9ZTd6hEIc2kw2.jpg', 'credit_id': '5913313c9251414ead052e40', 'department': 'Sound', 'job': 'Playback Singer'}]"

In [229]:
import ast
import pandas as pd

def fetch_director(text):
    directors = []
    try:
        data_list = ast.literal_eval(text)
        
        if isinstance(data_list, list):
            for item in data_list:
                if item.get('department') == 'Directing':
                    directors.append(item.get('original_name'))
    except (ValueError, SyntaxError) as e:
        print(f"Error parsing input: {e}")
    return directors

In [230]:
df['crew'] = df['crew'].apply(fetch_director)

# Delete rows where the directors list is empty

df = df[df['crew'].apply(lambda x: isinstance(x, list) and len(x) > 0)]

Error parsing input: unterminated string literal (detected at line 1) (<unknown>, line 1)

In [231]:
df['original_language']=df['original_language'].apply(lambda x: [x])

In [232]:
df

,movie_id,title,overview,genres,production_companies,cast,crew,original_language
0,783461,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...","[Action, Comedy, Crime]","[Ellipsis Entertainment, Sony Pictures Films I...","[Taapsee Pannu, Tahir Raj Bhasin, Shreya Dhanw...",[Aakash Bhatia],[hi]
1,592508,Sooryavanshi,"A fearless, faithful albeit slightly forgetful...","[Action, Crime, Thriller]","[Reliance Entertainment, Dharma Productions, R...","[Akshay Kumar, Katrina Kaif, Ajay Devgn]",[Rohit Shetty],[hi]
3,26022,My Name Is Khan,"Rizwan Khan, a Muslim from the Borivali sectio...","[Drama, Romance]","[Fox Searchlight Pictures, Red Chillies Entert...","[Shah Rukh Khan, Kajol, Jimmy Shergill]","[Karan Johar, Karan Malhotra, Varun Dhawan, Ab...",[hi]
4,767377,Dhamaka,When a cynical ex-TV news anchor gets an alarm...,"[Thriller, Drama, Crime]","[Lotte Entertainment, RSVP Movies, Ram Madhvan...","[Kartik Aaryan, Amruta Subhash, Mrunal Thakur]","[Ram Madhvani, Manohar Verma]",[hi]
5,496331,Brahmāstra Part One: Shiva,The story of Shiva – a young man on the brink ...,"[Action, Adventure, Fantasy]","[Star Studios, Prime Focus, Dharma Productions...","[Ranbir Kapoor, Alia Bhatt, Mouni Roy]",[Ayan Mukerji],[hi]
...,...,...,...,...,...,...,...,...
10182,667969,Birds of Paradise,Two dancers at an elite ballet academy in Pari...,[Drama],"[Big Indie Pictures, Anonymous Content, Amazon...","[Diana Silvers, Kristine Froseth, Eva Lomby]",[Sarah Adina Smith],[en]
10183,736820,Confidential Assignment 2: International,Follows Rim Chul Ryung heading back to South K...,"[Action, Comedy]","[CJ Entertainment, JK Film]","[Hyun Bin, Yoo Hae-jin, Yoona]",[Lee Suk-hoon],[ko]
10184,354861,Father Figures,Upon learning that their mother has been lying...,[Comedy],"[Alcon Entertainment, The Montecito Picture Co...","[Owen Wilson, Ed Helms, J.K. Simmons]","[Lawrence Sher, Gail Hunter]",[en]
10185,17687,The Public Enemy,"Two young Chicago hoodlums, Tom Powers and Mat...","[Crime, Drama]","[Warner Bros. Pictures, The Vitaphone Corporat...","[James Cagney, Jean Harlow, Edward Woods]",[William A. Wellman],[en]
10186,24739,Miracle Mile,"After 30 years of searching, Harry has finally...","[Romance, Science Fiction, Thriller, Drama]","[Hemdale Film, Miracle Mile Productions Inc.]","[Anthony Edwards, Mare Winningham, John Agar]",[Steve De Jarnatt],[en]

In [233]:
import re

def remove_noise(text):
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text

In [234]:

def remove_whitespaces(text):
    return [re.sub(r'\s+', '', word) for word in text]

df['cast']=df['cast'].apply(remove_whitespaces)
df['crew']=df['crew'].apply(remove_whitespaces)

In [235]:
df['overview']=df['overview'].apply(remove_noise)
df['title_info']=df['title'].apply(remove_noise)

In [236]:
df['overview']=df['overview'].apply(lambda X:X.split( ))
df['title_info']=df['title_info'].apply(lambda X:X.split( ))

In [237]:
df['data']=df['title_info']+df['original_language']+df['cast']+df['crew']+df['production_companies']+df['genres']+df['overview']

In [238]:
new_df=df[['movie_id','title','data']]

In [239]:
new_df

,movie_id,title,data
0,783461,Looop Lapeta,"[Looop, Lapeta, hi, TaapseePannu, TahirRajBhas..."
1,592508,Sooryavanshi,"[Sooryavanshi, hi, AkshayKumar, KatrinaKaif, A..."
3,26022,My Name Is Khan,"[My, Name, Is, Khan, hi, ShahRukhKhan, Kajol, ..."
4,767377,Dhamaka,"[Dhamaka, hi, KartikAaryan, AmrutaSubhash, Mru..."
5,496331,Brahmāstra Part One: Shiva,"[Brahm, stra, Part, One, Shiva, hi, RanbirKapo..."
...,...,...,...
10182,667969,Birds of Paradise,"[Birds, of, Paradise, en, DianaSilvers, Kristi..."
10183,736820,Confidential Assignment 2: International,"[Confidential, Assignment, International, ko, ..."
10184,354861,Father Figures,"[Father, Figures, en, OwenWilson, EdHelms, J.K..."
10185,17687,The Public Enemy,"[The, Public, Enemy, en, JamesCagney, JeanHarl..."
10186,24739,Miracle Mile,"[Miracle, Mile, en, AnthonyEdwards, MareWinnin..."

In [240]:
new_df=new_df.reset_index()
new_df=new_df.drop('index',axis=1)

In [241]:
new_df

,movie_id,title,data
0,783461,Looop Lapeta,"[Looop, Lapeta, hi, TaapseePannu, TahirRajBhas..."
1,592508,Sooryavanshi,"[Sooryavanshi, hi, AkshayKumar, KatrinaKaif, A..."
2,26022,My Name Is Khan,"[My, Name, Is, Khan, hi, ShahRukhKhan, Kajol, ..."
3,767377,Dhamaka,"[Dhamaka, hi, KartikAaryan, AmrutaSubhash, Mru..."
4,496331,Brahmāstra Part One: Shiva,"[Brahm, stra, Part, One, Shiva, hi, RanbirKapo..."
...,...,...,...
10108,667969,Birds of Paradise,"[Birds, of, Paradise, en, DianaSilvers, Kristi..."
10109,736820,Confidential Assignment 2: International,"[Confidential, Assignment, International, ko, ..."
10110,354861,Father Figures,"[Father, Figures, en, OwenWilson, EdHelms, J.K..."
10111,17687,The Public Enemy,"[The, Public, Enemy, en, JamesCagney, JeanHarl..."
10112,24739,Miracle Mile,"[Miracle, Mile, en, AnthonyEdwards, MareWinnin..."

In [242]:
new_df['data'].values

array([list(['Looop', 'Lapeta', 'hi', 'TaapseePannu', 'TahirRajBhasin', 'ShreyaDhanwanthary', 'AakashBhatia', 'Ellipsis Entertainment', 'Sony Pictures Films India', 'Action', 'Comedy', 'Crime', 'When', 'her', 'boyfriend', 'loses', 'a', 'mobster', 's', 'cash', 'Savi', 'races', 'against', 'the', 'clock', 'to', 'save', 'the', 'day', 'if', 'only', 'she', 'can', 'break', 'out', 'of', 'a', 'curious', 'cycle', 'of', 'dead', 'ends']),
       list(['Sooryavanshi', 'hi', 'AkshayKumar', 'KatrinaKaif', 'AjayDevgn', 'RohitShetty', 'Reliance Entertainment', 'Dharma Productions', 'Rohit Shetty Productionz', 'Action', 'Crime', 'Thriller', 'A', 'fearless', 'faithful', 'albeit', 'slightly', 'forgetful', 'Mumbai', 'cop', 'Veer', 'Sooryavanshi', 'the', 'chief', 'of', 'the', 'Anti', 'Terrorism', 'Squad', 'in', 'India', 'pulls', 'out', 'all', 'the', 'stops', 'and', 'stunts', 'to', 'thwart', 'a', 'major', 'conspiracy', 'to', 'attack', 'his', 'city']),
       list(['My', 'Name', 'Is', 'Khan', 'hi', 'ShahRukhKhan', 'Kajol', 'JimmyShergill', 'KaranJohar', 'KaranMalhotra', 'VarunDhawan', 'AbhishekVarman', 'UrvashiShah', 'EktaPathakMalhotra', 'RohitSharma', 'SantinoMorea', 'Fox Searchlight Pictures', 'Red Chillies Entertainment', 'Star Studios', 'Dharma Productions', 'Drama', 'Romance', 'Rizwan', 'Khan', 'a', 'Muslim', 'from', 'the', 'Borivali', 'section', 'of', 'Mumbai', 'has', 'Asperger', 's', 'syndrome', 'He', 'marries', 'a', 'Hindu', 'single', 'mother', 'Mandira', 'in', 'San', 'Francisco', 'After', 'Rizwan', 'is', 'detained', 'by', 'authorities', 'at', 'LAX', 'who', 'treat', 'him', 'as', 'a', 'terrorist', 'because', 'of', 'his', 'condition', 'and', 'his', 'race']),
       ...,
       list(['Father', 'Figures', 'en', 'OwenWilson', 'EdHelms', 'J.K.Simmons', 'LawrenceSher', 'GailHunter', 'Alcon Entertainment', 'The Montecito Picture Company', 'DMG Entertainment', 'Comedy', 'Upon', 'learning', 'that', 'their', 'mother', 'has', 'been', 'lying', 'to', 'them', 'for', 'years', 'about', 'their', 'allegedly', 'deceased', 'father', 'two', 'fraternal', 'twin', 'brothers', 'hit', 'the', 'road', 'in', 'order', 'to', 'find', 'him']),
       list(['The', 'Public', 'Enemy', 'en', 'JamesCagney', 'JeanHarlow', 'EdwardWoods', 'WilliamA.Wellman', 'Warner Bros. Pictures', 'The Vitaphone Corporation', 'Crime', 'Drama', 'Two', 'young', 'Chicago', 'hoodlums', 'Tom', 'Powers', 'and', 'Matt', 'Doyle', 'rise', 'up', 'from', 'their', 'poverty', 'stricken', 'slum', 'life', 'to', 'become', 'petty', 'thieves', 'bootleggers', 'and', 'cold', 'blooded', 'killers', 'But', 'with', 'street', 'notoriety', 'and', 'newfound', 'wealth', 'the', 'duo', 'feels', 'the', 'heat', 'from', 'the', 'cops', 'and', 'rival', 'gangsters', 'both', 'Despite', 'his', 'ruthless', 'criminal', 'reputation', 'Tom', 'tries', 'to', 'remain', 'connected', 'to', 'his', 'family', 'however', 'gang', 'warfare', 'and', 'the', 'need', 'for', 'revenge', 'eventually', 'pull', 'him', 'away']),
       list(['Miracle', 'Mile', 'en', 'AnthonyEdwards', 'MareWinningham', 'JohnAgar', 'SteveDeJarnatt', 'Hemdale Film', 'Miracle Mile Productions Inc.', 'Romance', 'Science Fiction', 'Thriller', 'Drama', 'After', 'years', 'of', 'searching', 'Harry', 'has', 'finally', 'met', 'the', 'girl', 'of', 'his', 'dreams', 'Unfortunately', 'before', 'they', 'even', 'have', 'a', 'chance', 'to', 'go', 'on', 'their', 'first', 'date', 'Harry', 'intercepts', 'some', 'chilling', 'news', 'WWIII', 'has', 'begun', 'and', 'nuclear', 'missiles', 'will', 'destroy', 'Los', 'Angeles', 'in', 'less', 'than', 'an', 'hour'])],
      dtype=object)

In [243]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

new_df['data'] = new_df['data'].apply(lambda text: [lemmatizer.lemmatize(x.lower()) for x in text])

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [244]:
new_df

,movie_id,title,data
0,783461,Looop Lapeta,"[looop, lapeta, hi, taapseepannu, tahirrajbhas..."
1,592508,Sooryavanshi,"[sooryavanshi, hi, akshaykumar, katrinakaif, a..."
2,26022,My Name Is Khan,"[my, name, is, khan, hi, shahrukhkhan, kajol, ..."
3,767377,Dhamaka,"[dhamaka, hi, kartikaaryan, amrutasubhash, mru..."
4,496331,Brahmāstra Part One: Shiva,"[brahm, stra, part, one, shiva, hi, ranbirkapo..."
...,...,...,...
10108,667969,Birds of Paradise,"[bird, of, paradise, en, dianasilvers, kristin..."
10109,736820,Confidential Assignment 2: International,"[confidential, assignment, international, ko, ..."
10110,354861,Father Figures,"[father, figure, en, owenwilson, edhelms, j.k...."
10111,17687,The Public Enemy,"[the, public, enemy, en, jamescagney, jeanharl..."
10112,24739,Miracle Mile,"[miracle, mile, en, anthonyedwards, marewinnin..."

In [245]:
new_df['data'] = new_df['data'].apply(lambda x: ' '.join(x))

In [246]:
new_df['data'][1]

'sooryavanshi hi akshaykumar katrinakaif ajaydevgn rohitshetty reliance entertainment dharma productions rohit shetty productionz action crime thriller a fearless faithful albeit slightly forgetful mumbai cop veer sooryavanshi the chief of the anti terrorism squad in india pull out all the stop and stunt to thwart a major conspiracy to attack his city'

In [247]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(stop_words='english',ngram_range=(1,5))

features_data=cv.fit_transform(new_df['data'])

In [248]:
features_data.shape

(10113, 1556158)

In [249]:
from sklearn.metrics.pairwise import cosine_similarity
simularity=cosine_similarity(features_data)
simularity

array([[1.        , 0.0313235 , 0.02186739, ..., 0.02112886, 0.00997758,
        0.        ],
       [0.0313235 , 1.        , 0.02876846, ..., 0.01235416, 0.01312637,
        0.01023021],
       [0.02186739, 0.02876846, 1.        , ..., 0.02156154, 0.00763643,
        0.02231832],
       ...,
       [0.02112886, 0.01235416, 0.02156154, ..., 1.        , 0.00491901,
        0.02300219],
       [0.00997758, 0.01312637, 0.00763643, ..., 0.00491901, 1.        ,
        0.00814666],
       [0.        , 0.01023021, 0.02231832, ..., 0.02300219, 0.00814666,
        1.        ]])

In [250]:
def recommendation(text):
    idx=new_df[new_df['title'] == text].index[0]
    cs=simularity[idx]
    neighbors=sorted(list(enumerate(cs)),reverse=True,key=lambda x:x[1])[1:11]
    
    for i in neighbors:
        print(new_df.iloc[i[0]].title)

In [257]:
recommendation('Man of Steel')

Justice League
Max Steel
Mad Max: Fury Road
Batman v Superman: Dawn of Justice
Superman Returns
The Space Between Us
Battle at Big Rock
Stargate
Deathstroke: Knights & Dragons - The Movie
Suicide Squad

In [252]:
import pickle

pickle.dump(new_df.to_dict(),open('movies_data.pkl','wb'))

In [253]:
pickle.dump(simularity,open('similarity.pkl','wb'))

In [256]:
print("done")

done